/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovoIncidenteRouteImport } from './routes/novo-incidente'
import { Route as IncidentesIndexRouteImport } from './routes/incidentes.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoIncidenteRoute = NovoIncidenteRouteImport.update({
  id: '/novo-incidente',
  path: '/novo-incidente',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesIndexRoute = IncidentesIndexRouteImport.update({
  id: '/incidentes/',
  path: '/incidentes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/novo-incidente': typeof NovoIncidenteRoute
  '/incidentes/': typeof IncidentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/novo-incidente': typeof NovoIncidenteRoute
  '/incidentes': typeof IncidentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/novo-incidente': typeof NovoIncidenteRoute
  '/incidentes/': typeof IncidentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/novo-incidente' | '/incidentes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/novo-incidente' | '/incidentes'
  id: '__root__' | '/' | '/novo-incidente' | '/incidentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovoIncidenteRoute: typeof NovoIncidenteRoute
  IncidentesIndexRoute: typeof IncidentesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-incidente': {
      id: '/novo-incidente'
      path: '/novo-incidente'
      fullPath: '/novo-incidente'
      preLoaderRoute: typeof NovoIncidenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes/': {
      id: '/incidentes/'
      path: '/incidentes'
      fullPath: '/incidentes/'
      preLoaderRoute: typeof IncidentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovoIncidenteRoute: NovoIncidenteRoute,
  IncidentesIndexRoute: IncidentesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
