/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbrirProtocoloRouteImport } from './routes/abrir-protocolo'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardsEDonosRouteImport } from './routes/cards-e-donos'
import { Route as MeusProtocolosRouteImport } from './routes/meus-protocolos'
import { Route as ProtocolosDosMeusCardsRouteImport } from './routes/protocolos-dos-meus-cards'
import { Route as TodosOsProtocolosRouteImport } from './routes/todos-os-protocolos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirProtocoloRoute = AbrirProtocoloRouteImport.update({
  id: '/abrir-protocolo',
  path: '/abrir-protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsEDonosRoute = CardsEDonosRouteImport.update({
  id: '/cards-e-donos',
  path: '/cards-e-donos',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusProtocolosRoute = MeusProtocolosRouteImport.update({
  id: '/meus-protocolos',
  path: '/meus-protocolos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolosDosMeusCardsRoute = ProtocolosDosMeusCardsRouteImport.update({
  id: '/protocolos-dos-meus-cards',
  path: '/protocolos-dos-meus-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosOsProtocolosRoute = TodosOsProtocolosRouteImport.update({
  id: '/todos-os-protocolos',
  path: '/todos-os-protocolos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir-protocolo': typeof AbrirProtocoloRoute
  '/administracao': typeof AdministracaoRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/cards-e-donos': typeof CardsEDonosRoute
  '/meus-protocolos': typeof MeusProtocolosRoute
  '/protocolos-dos-meus-cards': typeof ProtocolosDosMeusCardsRoute
  '/todos-os-protocolos': typeof TodosOsProtocolosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir-protocolo': typeof AbrirProtocoloRoute
  '/administracao': typeof AdministracaoRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/cards-e-donos': typeof CardsEDonosRoute
  '/meus-protocolos': typeof MeusProtocolosRoute
  '/protocolos-dos-meus-cards': typeof ProtocolosDosMeusCardsRoute
  '/todos-os-protocolos': typeof TodosOsProtocolosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir-protocolo': typeof AbrirProtocoloRoute
  '/administracao': typeof AdministracaoRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/cards-e-donos': typeof CardsEDonosRoute
  '/meus-protocolos': typeof MeusProtocolosRoute
  '/protocolos-dos-meus-cards': typeof ProtocolosDosMeusCardsRoute
  '/todos-os-protocolos': typeof TodosOsProtocolosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir-protocolo'
    | '/administracao'
    | '/analytics'
    | '/auth'
    | '/cards-e-donos'
    | '/meus-protocolos'
    | '/protocolos-dos-meus-cards'
    | '/todos-os-protocolos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir-protocolo'
    | '/administracao'
    | '/analytics'
    | '/auth'
    | '/cards-e-donos'
    | '/meus-protocolos'
    | '/protocolos-dos-meus-cards'
    | '/todos-os-protocolos'
  id:
    | '__root__'
    | '/'
    | '/abrir-protocolo'
    | '/administracao'
    | '/analytics'
    | '/auth'
    | '/cards-e-donos'
    | '/meus-protocolos'
    | '/protocolos-dos-meus-cards'
    | '/todos-os-protocolos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirProtocoloRoute: typeof AbrirProtocoloRoute
  AdministracaoRoute: typeof AdministracaoRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CardsEDonosRoute: typeof CardsEDonosRoute
  MeusProtocolosRoute: typeof MeusProtocolosRoute
  ProtocolosDosMeusCardsRoute: typeof ProtocolosDosMeusCardsRoute
  TodosOsProtocolosRoute: typeof TodosOsProtocolosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir-protocolo': {
      id: '/abrir-protocolo'
      path: '/abrir-protocolo'
      fullPath: '/abrir-protocolo'
      preLoaderRoute: typeof AbrirProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards-e-donos': {
      id: '/cards-e-donos'
      path: '/cards-e-donos'
      fullPath: '/cards-e-donos'
      preLoaderRoute: typeof CardsEDonosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-protocolos': {
      id: '/meus-protocolos'
      path: '/meus-protocolos'
      fullPath: '/meus-protocolos'
      preLoaderRoute: typeof MeusProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolos-dos-meus-cards': {
      id: '/protocolos-dos-meus-cards'
      path: '/protocolos-dos-meus-cards'
      fullPath: '/protocolos-dos-meus-cards'
      preLoaderRoute: typeof ProtocolosDosMeusCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos-os-protocolos': {
      id: '/todos-os-protocolos'
      path: '/todos-os-protocolos'
      fullPath: '/todos-os-protocolos'
      preLoaderRoute: typeof TodosOsProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirProtocoloRoute: AbrirProtocoloRoute,
  AdministracaoRoute: AdministracaoRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CardsEDonosRoute: CardsEDonosRoute,
  MeusProtocolosRoute: MeusProtocolosRoute,
  ProtocolosDosMeusCardsRoute: ProtocolosDosMeusCardsRoute,
  TodosOsProtocolosRoute: TodosOsProtocolosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
