-- SAFRA-C06 — Seed canônico dos 11 cenários da Matriz v3
-- Fonte: EDB06 - Matriz Contingencia v3.xlsx | aba: Matriz de Contingência | SHA256: b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6
-- Textos de negócio preservados literalmente. criticality permanece NULL por GI-SAFRA-001.
-- SLA-alvo textual fica preservado em source_reference; scenario_slas não é preenchido
-- porque start_event/end_event não constam explicitamente na Matriz v3.
begin;

insert into public.operational_areas(code,name,is_active) values ('LOGISTICA','Logística',true) on conflict (code) do nothing;
insert into public.operational_areas(code,name,is_active) values ('POS_VENDAS','Pós-Vendas',true) on conflict (code) do nothing;
insert into public.operational_areas(code,name,is_active) values ('E_COMMERCE','E-Commerce',true) on conflict (code) do nothing;
insert into public.operational_areas(code,name,is_active) values ('COMERCIAL','Comercial',true) on conflict (code) do nothing;
insert into public.operational_areas(code,name,is_active) values ('TI','TI',true) on conflict (code) do nothing;
insert into public.operational_areas(code,name,is_active) values ('DAF','DAF',true) on conflict (code) do nothing;
insert into public.operational_areas(code,name,is_active) values ('PCP','PCP',true) on conflict (code) do nothing;

insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-01','Intelipost + Painel de Protocolos','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-02','Intelipost + Painel','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-03','Cockpit + Intelipost + Painel','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-04','Cockpit de Faturamento e Expedição (Protheus) + Painel','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-05','Mensageria/Cockpit + Intelipost + Painel','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-06','Monitoramento de TI + comunicação às áreas','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-07','WMS/Protheus (estoque) + Cockpit + Painel','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-08','Protheus (PCP/estoque) + Painel','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-09','Cockpit/Painel','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;
insert into public.systems(code,name,description,is_active) values ('MATRIX-TOOL-10','Painel de Protocolos (BI) + Cockpit','Ferramenta conforme EDB06 - Matriz Contingencia v3.xlsx',true) on conflict (name) do nothing;

insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-01','Insucesso de entrega','ACTIVE',a.id from public.operational_areas a where a.code='LOGISTICA' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-02','Transportadora fora do ar','ACTIVE',a.id from public.operational_areas a where a.code='LOGISTICA' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-03','Atraso (+48h) sem causa','ACTIVE',a.id from public.operational_areas a where a.code='LOGISTICA' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-04','Pedido pago não integrado
("limbo" de entrada)','ACTIVE',a.id from public.operational_areas a where a.code='TI' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-05','Tracking falso
(status ≠ físico)','ACTIVE',a.id from public.operational_areas a where a.code='TI' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-06','ERP indisponível/travado no pico','ACTIVE',a.id from public.operational_areas a where a.code='TI' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-07','Divergência saldo físico × virtual','ACTIVE',a.id from public.operational_areas a where a.code='LOGISTICA' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-08','Falha de NF-e / bloqueio fiscal','ACTIVE',a.id from public.operational_areas a where a.code='TI' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-09','Ruptura de estoque de título (curva A)','ACTIVE',a.id from public.operational_areas a where a.code='PCP' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-10','Colapso da fila de picking / esteira','ACTIVE',a.id from public.operational_areas a where a.code='LOGISTICA' on conflict (code) do nothing;
insert into public.scenarios(code,name,lifecycle_status,responsible_area_id) select 'SAFRA-11','Pico de volume acima da capacidade','ACTIVE',a.id from public.operational_areas a where a.code='LOGISTICA' on conflict (code) do nothing;

insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='daniel.garcia@editoradobrasil.com.br' where sc.code='SAFRA-01' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='daniel.garcia@editoradobrasil.com.br' where sc.code='SAFRA-02' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='daniel.garcia@editoradobrasil.com.br' where sc.code='SAFRA-03' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='jiane.rodrigues@editoradobrasil.com.br' where sc.code='SAFRA-04' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='jiane.rodrigues@editoradobrasil.com.br' where sc.code='SAFRA-05' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='jiane.rodrigues@editoradobrasil.com.br' where sc.code='SAFRA-06' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='daniel.garcia@editoradobrasil.com.br' where sc.code='SAFRA-07' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='jiane.rodrigues@editoradobrasil.com.br' where sc.code='SAFRA-08' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='renato.paulo@editoradobrasil.com.br' where sc.code='SAFRA-09' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='daniel.garcia@editoradobrasil.com.br' where sc.code='SAFRA-10' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);
insert into public.scenario_owners(scenario_id,owner_id,assignment_reason) select sc.id,p.id,'Owner canônico conforme Matriz v3' from public.scenarios sc join private.safra_principals p on lower(p.corporate_email)='daniel.garcia@editoradobrasil.com.br' where sc.code='SAFRA-11' and not exists (select 1 from public.scenario_owners so where so.scenario_id=sc.id and so.valid_to is null);

insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Transportadora reporta falha de entrega na Intelipost.','Automático — Intelipost registra a falha e dispara alerta (≤ 2h).','1) Transportadora reporta a falha na Intelipost em até 2h.
2) Sistema avisa o cliente com clareza e transparência.
3) Endereço errado/ausência: nova tentativa agendada automaticamente.
4) Área de risco: análise imediata e conjunta entre Comercial (B2B) ou SAC (B2C).
5) Tratativa interna concluída em, no máximo, 48h.',null,null,'{"number":1,"code":"SAFRA-01","name":"Insucesso de entrega","trigger":"Transportadora reporta falha de entrega na Intelipost.","activation":"Automático — Intelipost registra a falha e dispara alerta (≤ 2h).","protocol":"1) Transportadora reporta a falha na Intelipost em até 2h.\n2) Sistema avisa o cliente com clareza e transparência.\n3) Endereço errado/ausência: nova tentativa agendada automaticamente.\n4) Área de risco: análise imediata e conjunta entre Comercial (B2B) ou SAC (B2C).\n5) Tratativa interna concluída em, no máximo, 48h.","responsible_area":"Logística","owner":"Daniel Garcia","impacted_areas":"Pós-Vendas, E-Commerce, Comercial","sla_target":"Falha reportada ≤ 2h;\ntratativa ≤ 48h","tool":"Intelipost + Painel de Protocolos","monitoring_visibility":"Fila de ocorrências de entrega na Intelipost; status e SLA (≤48h) no Painel mostram em que etapa está a tratativa.","validation_participants":"Daniel, Luis Fernando","mapping":"EDB05","source_row":5,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-01' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Sem coleta ou atualização de status de uma transportadora/OPL por mais de X h','Automático — Intelipost detecta ausência de coleta/atualização; ou aviso manual do parceiro.','1) Intelipost sinaliza a transportadora sem coleta/atualização.
2) Fretes aciona a liderança do parceiro exigindo retorno.
3) Sem solução, redireciona a carga para malha alternativa (ex.: OPL regional — Manaus/Nordeste).
4) Pós-Vendas comunica clientes impactados proativamente.
5) Incidente vira critério de avaliação do parceiro.',null,null,'{"number":2,"code":"SAFRA-02","name":"Transportadora fora do ar","trigger":"Sem coleta ou atualização de status de uma transportadora/OPL por mais de X h","activation":"Automático — Intelipost detecta ausência de coleta/atualização; ou aviso manual do parceiro.","protocol":"1) Intelipost sinaliza a transportadora sem coleta/atualização.\n2) Fretes aciona a liderança do parceiro exigindo retorno.\n3) Sem solução, redireciona a carga para malha alternativa (ex.: OPL regional — Manaus/Nordeste).\n4) Pós-Vendas comunica clientes impactados proativamente.\n5) Incidente vira critério de avaliação do parceiro.","responsible_area":"Logística","owner":"Daniel Garcia","impacted_areas":"TI, Comercial","sla_target":"Plano B de malha ≤ 4h;\nclientes comunicados","tool":"Intelipost + Painel","monitoring_visibility":"Status por transportadora/região no Painel; volume parado por parceiro.","validation_participants":"Daniel, Jiane/Bichir","mapping":"EDB06","source_row":10,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-02' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Pedido sem movimentação por 48h (alerta automático).','Automático — alerta do Cockpit/Intelipost para pedido parado há 48h.','1) Alerta automático para pedidos sem movimentação há 48h.
2) Cobrança imediata à transportadora, com retorno exigido em 4h.
3) Sem resposta, escala direto à liderança do parceiro logístico.
4) Pós-Vendas contata o cliente proativamente, antes da reclamação.
5) Ocorrências alimentam o ritual semanal para evitar reincidências.',null,null,'{"number":3,"code":"SAFRA-03","name":"Atraso (+48h) sem causa","trigger":"Pedido sem movimentação por 48h (alerta automático).","activation":"Automático — alerta do Cockpit/Intelipost para pedido parado há 48h.","protocol":"1) Alerta automático para pedidos sem movimentação há 48h.\n2) Cobrança imediata à transportadora, com retorno exigido em 4h.\n3) Sem resposta, escala direto à liderança do parceiro logístico.\n4) Pós-Vendas contata o cliente proativamente, antes da reclamação.\n5) Ocorrências alimentam o ritual semanal para evitar reincidências.","responsible_area":"Logística","owner":"Daniel Garcia","impacted_areas":"Pós-Vendas, Comercial","sla_target":"Alerta a partir de 48h;\nretorno da transportadora ≤ 4h","tool":"Cockpit + Intelipost + Painel","monitoring_visibility":"Fila \"sem movimentação 48h\"; status da cobrança (retorno ≤4h) e do escalonamento no Painel.","validation_participants":"Daniel, Luis Fernando","mapping":"EDB05","source_row":15,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-03' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Pagamento aprovado no GoDeep sem espelho correspondente no Protheus após X min.','Automático — monitor de integração detecta o pedido pago sem espelho no Protheus.','1) Monitor de integração detecta o pedido pago sem espelho no Protheus.
2) Reprocessamento automático da fila GoDeep → Protheus.
3) Persistindo, TI trata manualmente e registra a ocorrência.
4) Pedido só é confirmado ao cliente após integração efetiva (sem status falso).
5) Causa-raiz registrada e levada ao ritual para reduzir reincidência.',null,null,'{"number":4,"code":"SAFRA-04","name":"Pedido pago não integrado\n(\"limbo\" de entrada)","trigger":"Pagamento aprovado no GoDeep sem espelho correspondente no Protheus após X min.","activation":"Automático — monitor de integração detecta o pedido pago sem espelho no Protheus.","protocol":"1) Monitor de integração detecta o pedido pago sem espelho no Protheus.\n2) Reprocessamento automático da fila GoDeep → Protheus.\n3) Persistindo, TI trata manualmente e registra a ocorrência.\n4) Pedido só é confirmado ao cliente após integração efetiva (sem status falso).\n5) Causa-raiz registrada e levada ao ritual para reduzir reincidência.","responsible_area":"TI","owner":"Jiane Rodrigues","impacted_areas":"E-Commerce","sla_target":"Detecção em tempo real;\nreprocesso/tratativa ≤ 2h","tool":"Cockpit de Faturamento e Expedição (Protheus) + Painel","monitoring_visibility":"Fila de pedidos \"em limbo\" no Cockpit; reprocesso e SLA (≤2h) no Painel.","validation_participants":"Jiane/Bichir, Leo","mapping":"EDB06","source_row":20,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-04' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Status "despachado/enviado" disparado sem evento físico (separação/coleta) correspondente.','Automático — regra de mensageria detecta status sem evento físico e retém a notificação.','1) Regra de mensageria barra o "despachado" sem confirmação física.
2) Sistema cruza status sistêmico × evento físico antes de notificar.
3) Divergência detectada: notificação ao cliente fica retida até corrigir.
4) TI + Logística corrigem o ponto de atualização de status.
5) Cliente só recebe o status real (tracking confiável na Intelipost).',null,null,'{"number":5,"code":"SAFRA-05","name":"Tracking falso\n(status ≠ físico)","trigger":"Status \"despachado/enviado\" disparado sem evento físico (separação/coleta) correspondente.","activation":"Automático — regra de mensageria detecta status sem evento físico e retém a notificação.","protocol":"1) Regra de mensageria barra o \"despachado\" sem confirmação física.\n2) Sistema cruza status sistêmico × evento físico antes de notificar.\n3) Divergência detectada: notificação ao cliente fica retida até corrigir.\n4) TI + Logística corrigem o ponto de atualização de status.\n5) Cliente só recebe o status real (tracking confiável na Intelipost).","responsible_area":"TI","owner":"Jiane Rodrigues","impacted_areas":"Logística, E-Commerce","sla_target":"Correção antes de avisar o cliente;\ntratativa ≤ 4h","tool":"Mensageria/Cockpit + Intelipost + Painel","monitoring_visibility":"Lista de divergências status × físico; SLA de correção no Painel.","validation_participants":"Daniel, Jiane/Bichir","mapping":"EDB06","source_row":25,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-05' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Indisponibilidade ou lentidão crítica do Protheus (monitor de disponibilidade/performance).','Automático — monitoramento de disponibilidade/performance do Protheus dispara alerta.','1) Monitoramento dispara alerta de indisponibilidade/lentidão crítica.
2) TI (Infra) + DFS acionam o plano de continuidade (ex.: isolar relatórios da produção).
3) Operação migra para procedimento de contingência pré-definido.
4) Comunicação imediata às áreas impactadas (CD, Faturamento, SAC).
5) Pós-incidente: causa-raiz e ação levadas à governança de GMUD.',null,null,'{"number":6,"code":"SAFRA-06","name":"ERP indisponível/travado no pico","trigger":"Indisponibilidade ou lentidão crítica do Protheus (monitor de disponibilidade/performance).","activation":"Automático — monitoramento de disponibilidade/performance do Protheus dispara alerta.","protocol":"1) Monitoramento dispara alerta de indisponibilidade/lentidão crítica.\n2) TI (Infra) + DFS acionam o plano de continuidade (ex.: isolar relatórios da produção).\n3) Operação migra para procedimento de contingência pré-definido.\n4) Comunicação imediata às áreas impactadas (CD, Faturamento, SAC).\n5) Pós-incidente: causa-raiz e ação levadas à governança de GMUD.","responsible_area":"TI","owner":"Jiane Rodrigues","impacted_areas":"Logística, Comercial","sla_target":"Plano de continuidade ≤ 30 min;\npós-mortem ≤ 48h","tool":"Monitoramento de TI + comunicação às áreas","monitoring_visibility":"Status do incidente (aberto → normalizado) e do plano de continuidade; pós-mortem na governança de GMUD.","validation_participants":"Jiane/Bichir","mapping":"EDB06","source_row":30,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-06' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Separação não localiza item com saldo no sistema (ou inventário aponta divergência).','Misto — separação registra a divergência (manual) ou inventário cíclico aponta (sistêmico).','1) Operação registra a divergência no ato da separação.
2) Inventário faz contagem pontual (cíclico) do endereço/SKU.
3) TI/Estoque ajustam o saldo e reendereçam se necessário.
4) Pedido afetado é repriorizado para não estourar o SLA de entrega.
5) Reincidência por SKU/endereço monitorada (curva A primeiro).',null,null,'{"number":7,"code":"SAFRA-07","name":"Divergência saldo físico × virtual","trigger":"Separação não localiza item com saldo no sistema (ou inventário aponta divergência).","activation":"Misto — separação registra a divergência (manual) ou inventário cíclico aponta (sistêmico).","protocol":"1) Operação registra a divergência no ato da separação.\n2) Inventário faz contagem pontual (cíclico) do endereço/SKU.\n3) TI/Estoque ajustam o saldo e reendereçam se necessário.\n4) Pedido afetado é repriorizado para não estourar o SLA de entrega.\n5) Reincidência por SKU/endereço monitorada (curva A primeiro).","responsible_area":"Logística","owner":"Daniel Garcia","impacted_areas":"TI, E-Commerce","sla_target":"Acerto do saldo ≤ 24h;\nreprocesso do pedido no mesmo dia","tool":"WMS/Protheus (estoque) + Cockpit + Painel","monitoring_visibility":"Ocorrências de divergência por SKU/endereço; SLA de acerto (≤24h) e reincidência (curva A) no Painel.","validation_participants":"Daniel, Jiane/Bichir","mapping":"EDB06","source_row":35,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-07' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Pedido faturável parado por rejeição da SEFAZ ou bloqueio fiscal/cadastral.','Automático — Cockpit sinaliza pedido faturável retido por rejeição/bloqueio.','1) Cockpit lista o pedido retido na fila de faturamento.
2) Fiscal/Financeiro identifica a causa (rejeição SEFAZ, cadastro, tributação).
3) Correção e reenvio da NF-e.
4) Persistindo, escala para TI/parametrização fiscal.
5) Causa recorrente vira ajuste de cadastro/regra (governança).',null,null,'{"number":8,"code":"SAFRA-08","name":"Falha de NF-e / bloqueio fiscal","trigger":"Pedido faturável parado por rejeição da SEFAZ ou bloqueio fiscal/cadastral.","activation":"Automático — Cockpit sinaliza pedido faturável retido por rejeição/bloqueio.","protocol":"1) Cockpit lista o pedido retido na fila de faturamento.\n2) Fiscal/Financeiro identifica a causa (rejeição SEFAZ, cadastro, tributação).\n3) Correção e reenvio da NF-e.\n4) Persistindo, escala para TI/parametrização fiscal.\n5) Causa recorrente vira ajuste de cadastro/regra (governança).","responsible_area":"TI","owner":"Jiane Rodrigues","impacted_areas":"DAF","sla_target":"Liberar a NF ≤ 4h;\nsem perder a janela de expedição do dia","tool":"Cockpit de Faturamento e Expedição (Protheus) + Painel","monitoring_visibility":"Fila de pedidos \"retidos no faturamento\"; status e SLA no Painel.","validation_participants":"Eliana, Jiane/Bichir","mapping":"EDB06","source_row":40,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-08' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Saldo de SKU de alta demanda (curva A) abaixo do mínimo durante o pico.','Automático — alerta de saldo mínimo no Protheus/PCP para itens curva A.','1) Sistema alerta saldo abaixo do mínimo (curva A).
2) PCP/Suprimentos avaliam reposição e prazo de produção/compra.
3) Pedidos afetados sinalizados; consolidação por janela quando possível.
4) Comercial/atendimento alinham prazo realista (sem falsa promessa).
5) Item entra no plano de reposição priorizado.',null,null,'{"number":9,"code":"SAFRA-09","name":"Ruptura de estoque de título (curva A)","trigger":"Saldo de SKU de alta demanda (curva A) abaixo do mínimo durante o pico.","activation":"Automático — alerta de saldo mínimo no Protheus/PCP para itens curva A.","protocol":"1) Sistema alerta saldo abaixo do mínimo (curva A).\n2) PCP/Suprimentos avaliam reposição e prazo de produção/compra.\n3) Pedidos afetados sinalizados; consolidação por janela quando possível.\n4) Comercial/atendimento alinham prazo realista (sem falsa promessa).\n5) Item entra no plano de reposição priorizado.","responsible_area":"PCP","owner":"Renato de Paulo","impacted_areas":"Logística, Comercial","sla_target":"Reposição/realocação no dia;\nprazo realinhado com o cliente","tool":"Protheus (PCP/estoque) + Painel","monitoring_visibility":"Lista de SKUs em ruptura (curva A primeiro); status da reposição no Painel.","validation_participants":"Daniel, Renato","mapping":"EDB06","source_row":45,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-09' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Lead time de separação acima do limite / fila física travando a esteira no CD.','Automático — indicador de lead time/fila de separação acima do limite ','1) Indicador de fila/lead time dispara o alerta.
2) Supervisão do CD reprioriza e reforça turno/posição.
3) Consolidação por código promocional/janela para reduzir volume de separação.
4) Pedidos críticos (urgente/SLA curto) priorizados.
5) Gargalo recorrente vira ajuste de dimensionamento (Pessoas).',null,null,'{"number":10,"code":"SAFRA-10","name":"Colapso da fila de picking / esteira","trigger":"Lead time de separação acima do limite / fila física travando a esteira no CD.","activation":"Automático — indicador de lead time/fila de separação acima do limite ","protocol":"1) Indicador de fila/lead time dispara o alerta.\n2) Supervisão do CD reprioriza e reforça turno/posição.\n3) Consolidação por código promocional/janela para reduzir volume de separação.\n4) Pedidos críticos (urgente/SLA curto) priorizados.\n5) Gargalo recorrente vira ajuste de dimensionamento (Pessoas).","responsible_area":"Logística","owner":"Daniel Garcia","impacted_areas":"Comercial","sla_target":"Reforço/realocação imediata;\nfila normalizada no turno","tool":"Cockpit/Painel","monitoring_visibility":"Lead time de separação e tamanho da fila no Painel; mostra onde a esteira está parada.","validation_participants":"Daniel","mapping":"EDB06","source_row":50,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-10' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);
insert into public.scenario_versions(scenario_id,version_no,status,trigger_description,detection_description,protocol_text,expected_impact_summary,criticality,source_reference) select sc.id,1,'DRAFT','Volume de pedidos/dia acima do limiar planejado para a Safra.','Automático — volume diário cruza o limiar do plano (Painel/PCP).','1) Painel sinaliza volume acima do planejado.
2) PCP + Operação acionam o plano de pico (turnos/posições/parceiros).
3) Adequação de SLA B2C para aliviar o CD (prazos inteligentes).
4) Consolidação de carga reforçada.
5) Revisão diária enquanto durar o pico.',null,null,'{"number":11,"code":"SAFRA-11","name":"Pico de volume acima da capacidade","trigger":"Volume de pedidos/dia acima do limiar planejado para a Safra.","activation":"Automático — volume diário cruza o limiar do plano (Painel/PCP).","protocol":"1) Painel sinaliza volume acima do planejado.\n2) PCP + Operação acionam o plano de pico (turnos/posições/parceiros).\n3) Adequação de SLA B2C para aliviar o CD (prazos inteligentes).\n4) Consolidação de carga reforçada.\n5) Revisão diária enquanto durar o pico.","responsible_area":"Logística","owner":"Daniel Garcia","impacted_areas":"PCP, Comercial","sla_target":"Plano de pico acionado no dia;\nsem turnos extras não planejados","tool":"Painel de Protocolos (BI) + Cockpit","monitoring_visibility":"Volume diário × capacidade no Painel; gargalos por etapa.","validation_participants":"Daniel, Renato","mapping":"EDB06","source_row":55,"source_file":"EDB06 - Matriz Contingencia v3.xlsx","source_sheet":"Matriz de Contingência","source_sha256":"b0cca8cce835dbdc65ab0c30212fd89480d2cf51e9fb62d215ad1bde0963ead6"}' from public.scenarios sc where sc.code='SAFRA-11' and not exists (select 1 from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1);

insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='POS_VENDAS' where sc.code='SAFRA-01' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='E_COMMERCE' where sc.code='SAFRA-01' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='COMERCIAL' where sc.code='SAFRA-01' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Intelipost + Painel de Protocolos' where sc.code='SAFRA-01' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='TI' where sc.code='SAFRA-02' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='COMERCIAL' where sc.code='SAFRA-02' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Intelipost + Painel' where sc.code='SAFRA-02' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='POS_VENDAS' where sc.code='SAFRA-03' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='COMERCIAL' where sc.code='SAFRA-03' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Cockpit + Intelipost + Painel' where sc.code='SAFRA-03' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='E_COMMERCE' where sc.code='SAFRA-04' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Cockpit de Faturamento e Expedição (Protheus) + Painel' where sc.code='SAFRA-04' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='LOGISTICA' where sc.code='SAFRA-05' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='E_COMMERCE' where sc.code='SAFRA-05' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Mensageria/Cockpit + Intelipost + Painel' where sc.code='SAFRA-05' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='LOGISTICA' where sc.code='SAFRA-06' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='COMERCIAL' where sc.code='SAFRA-06' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Monitoramento de TI + comunicação às áreas' where sc.code='SAFRA-06' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='TI' where sc.code='SAFRA-07' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='E_COMMERCE' where sc.code='SAFRA-07' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='WMS/Protheus (estoque) + Cockpit + Painel' where sc.code='SAFRA-07' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='DAF' where sc.code='SAFRA-08' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Cockpit de Faturamento e Expedição (Protheus) + Painel' where sc.code='SAFRA-08' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='LOGISTICA' where sc.code='SAFRA-09' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='COMERCIAL' where sc.code='SAFRA-09' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Protheus (PCP/estoque) + Painel' where sc.code='SAFRA-09' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='COMERCIAL' where sc.code='SAFRA-10' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Cockpit/Painel' where sc.code='SAFRA-10' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='PCP' where sc.code='SAFRA-11' on conflict do nothing;
insert into public.scenario_version_impacted_areas(scenario_version_id,operational_area_id) select sv.id,a.id from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.operational_areas a on a.code='COMERCIAL' where sc.code='SAFRA-11' on conflict do nothing;
insert into public.scenario_version_systems(scenario_version_id,system_id,context) select sv.id,sy.id,'Ferramenta canônica da Matriz v3' from public.scenarios sc join public.scenario_versions sv on sv.scenario_id=sc.id and sv.version_no=1 join public.systems sy on sy.name='Painel de Protocolos (BI) + Cockpit' where sc.code='SAFRA-11' on conflict do nothing;

update public.scenario_versions sv set status='PUBLISHED' from public.scenarios sc where sv.scenario_id=sc.id and sv.version_no=1 and sv.status='DRAFT' and sc.code ~ '^SAFRA-(0[1-9]|1[01])$';
update public.scenarios sc set current_version_id=sv.id from public.scenario_versions sv where sv.scenario_id=sc.id and sv.version_no=1 and sv.status='PUBLISHED' and sc.code ~ '^SAFRA-(0[1-9]|1[01])$';

do $$ declare v_s integer; v_v integer; v_o integer; v_nullcrit integer; begin
 select count(*) into v_s from public.scenarios where code ~ '^SAFRA-(0[1-9]|1[01])$';
 select count(*) into v_v from public.scenario_versions sv join public.scenarios sc on sc.id=sv.scenario_id where sc.code ~ '^SAFRA-(0[1-9]|1[01])$' and sv.version_no=1 and sv.status='PUBLISHED';
 select count(*) into v_o from public.scenario_owners so join public.scenarios sc on sc.id=so.scenario_id where sc.code ~ '^SAFRA-(0[1-9]|1[01])$' and so.valid_to is null;
 select count(*) into v_nullcrit from public.scenario_versions sv join public.scenarios sc on sc.id=sv.scenario_id where sc.code ~ '^SAFRA-(0[1-9]|1[01])$' and sv.version_no=1 and sv.criticality is null;
 if v_s<>11 or v_v<>11 or v_o<>11 or v_nullcrit<>11 then raise exception 'C06 seed invariant failed: scenarios %, versions %, owners %, nullcrit %',v_s,v_v,v_o,v_nullcrit; end if;
end $$;
commit;
